/**
 * Flags that specify the state of a grid row or column.
 */
export enum RowColFlags {
    /** The row or column is visible. */
    Visible         = 0x1,
    /** The row or column can be resized. */
    AllowResizing   = 0x2,
    /** The row or column can be dragged to a new position with the mouse. */
    AllowDragging   = 0x4,
    /** The row or column can contain merged cells. */
    AllowMerging    = 0x8,
    /** The column can be sorted by clicking its header with the mouse. */
    AllowSorting    = 0x10,
    /** The column was generated automatically. */
    AutoGenerated   = 0x20,
    /** The group row is collapsed. */
    Collapsed       = 0x40,
    /** The row has a parent group that is collapsed. */
    ParentCollapsed = 0x80,
    /** The row or column is selected. */
    Selected        = 0x100,
    /** The row or column is read-only (cannot be edited). */
    ReadOnly        = 0x200,
    /** Cells in this row or column contain HTML text. */
    HtmlContent     = 0x400,
    /** Cells in this row or column may contain wrapped text. */
    WordWrap        = 0x800,
    /** Default settings for new rows. */
    RowDefault      = Visible | AllowResizing,
    /** Default settings for new columns. */
    ColumnDefault   = Visible | AllowDragging | AllowResizing | AllowSorting
}
